using System.Collections;
using AudioToolbox.EventTracer.Backends.Fmod;
using FMODUnity;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

namespace AudioToolbox.EventTracer.Tests.Fmod
{
    /// <summary>
    /// Each of the outcomes, provoked for real in FMOD.
    /// </summary>
    /// <remarks>
    /// The other half of the story. <c>OutcomeStateMachineTests</c> settles what a given
    /// sequence of signals means; this settles that FMOD actually produces that sequence
    /// when a sound is stolen, refused or virtualised. Callback ordering is where
    /// middleware documentation and middleware behaviour part company, and the only way
    /// to know is to make the engine do it.
    /// <para>
    /// The events these post are generated by <c>Tools/TraceFixture~</c>: each one is
    /// configured to make exactly one outcome reproducible — max instances of one with
    /// stealing set to None for a refusal, to Oldest for a steal, to Virtualize for a
    /// virtualisation. Re-run that script if this fixture stops finding them.
    /// </para>
    /// </remarks>
    [TestFixture]
    public sealed class FmodOutcomeTests
    {
        private const string Folder = "event:/AudioToolboxTrace/";
        private const string Basic2D = Folder + "Basic2D";
        private const string Spatial3D = Folder + "Spatial3D";
        private const string MaxOneReject = Folder + "MaxOneReject";
        private const string MaxOneSteal = Folder + "MaxOneSteal";
        private const string MaxOneVirtualize = Folder + "MaxOneVirtualize";

        /// <summary>
        /// Frames to give FMOD before deciding a callback is not coming.
        /// </summary>
        /// <remarks>
        /// Generous, and deliberately not tuned close to the observed latency. FMOD
        /// Studio updates asynchronously, so a callback crosses two thread hand-offs
        /// before the tracer sees it — measured at eight to fifteen frames here, and
        /// there is no reason to think a slower machine matches that. Waiting for the
        /// outcome rather than for a fixed number of frames is what keeps this fixture
        /// from being the flaky one nobody trusts.
        /// </remarks>
        private const int CallbackFrames = 150;

        [UnitySetUp]
        public IEnumerator SetUp()
        {
            AudioTraceRuntime.ResetForTests(new FmodRuntimeProbe(), new AudioTraceSettings
            {
                RecordCapacity = 512,
                MaxConcurrentVoices = 32,
                SignalQueueCapacity = 512,
                InternCapacity = 128,
                WriteToDisk = false,
                FlushIntervalSeconds = 60f,
                NaturalEndToleranceSeconds = 0.1,
            });

            Assert.That(
                AudioTrace.BackendId,
                Is.EqualTo("fmod"),
                "FMOD did not initialise; the rest of this fixture would be testing nothing");

            // Banks load asynchronously. Posting before they are in produces
            // HandleInvalid for every event, which would look like a mapping bug.
            for (var frame = 0; frame < 240 && !RuntimeManager.HaveAllBanksLoaded; frame++)
            {
                yield return null;
            }

            Assert.That(RuntimeManager.HaveAllBanksLoaded, Is.True, "FMOD banks never finished loading");

            RuntimeManager.StudioSystem.getEvent(Basic2D, out var description);

            Assert.That(
                description.isValid(),
                Is.True,
                $"{Basic2D} is missing. Run Tools/TraceFixture~/build-trace-fixture.ps1 against the FMOD project.");
        }

        [UnityTearDown]
        public IEnumerator TearDown()
        {
            AudioTraceRuntime.Shutdown();

            // Shutdown cuts every instance and clears its user data, but FMOD still has
            // to run an update or two before they are actually gone. Give it those before
            // the next test starts posting.
            yield return Settle();
        }

        private static IEnumerator Settle(int frames = 30)
        {
            for (var i = 0; i < frames; i++)
            {
                yield return null;
            }
        }

        /// <summary>
        /// Waits until a voice reaches <paramref name="expected"/>, then asserts it did.
        /// </summary>
        /// <remarks>
        /// Returns as soon as the outcome matches, so the fixture stays fast, and fails
        /// with the outcome it actually saw rather than with a timeout, so a failure says
        /// what FMOD did instead of only that it did not do the right thing in time.
        /// </remarks>
        private static IEnumerator AssertBecomes(AudioTraceHandle handle, PlaybackOutcome expected, string because = null)
        {
            for (var frame = 0; frame < CallbackFrames; frame++)
            {
                if (AudioTraceRuntime.GetOutcome(handle) == expected)
                {
                    yield break;
                }

                yield return null;
            }

            Assert.That(AudioTraceRuntime.GetOutcome(handle), Is.EqualTo(expected), because);
        }

        /// <summary>Waits out the callback budget, then asserts the outcome has not moved.</summary>
        private static IEnumerator AssertStaysAt(AudioTraceHandle handle, PlaybackOutcome expected, string because = null)
        {
            for (var frame = 0; frame < CallbackFrames; frame++)
            {
                Assert.That(AudioTraceRuntime.GetOutcome(handle), Is.EqualTo(expected), because);
                yield return null;
            }
        }

        [UnityTest]
        public IEnumerator AnEventThatDoesNotExist_IsHandleInvalid()
        {
            var handle = AudioTrace.Post(Folder + "ThisEventDoesNotExist");

            Assert.That(handle.IsValid, Is.False);

            yield return Settle();

            Assert.That(AudioTraceRuntime.GetOutcome(handle), Is.EqualTo(PlaybackOutcome.NotCalled));

            // The failed post still left a record; that is the whole point.
            var records = new System.Collections.Generic.List<AudioTraceRecord>();
            AudioTraceRuntime.SnapshotRecords(records);

            Assert.That(records[records.Count - 1].Outcome, Is.EqualTo(PlaybackOutcome.HandleInvalid));
            Assert.That(
                records[records.Count - 1].BackendResultCode,
                Is.EqualTo((int)FMOD.RESULT.ERR_EVENT_NOTFOUND),
                "FMOD's own result code should survive normalisation");
        }

        [UnityTest]
        public IEnumerator APlainEvent_IsStarted()
        {
            var handle = AudioTrace.Post(Basic2D);

            Assert.That(handle.IsValid, Is.True);

            yield return AssertBecomes(handle, PlaybackOutcome.Started);

            AudioTrace.Stop(handle);
        }

        [UnityTest]
        public IEnumerator StoppingPartWayThrough_IsStoppedEarly()
        {
            var handle = AudioTrace.Post(Basic2D);
            yield return AssertBecomes(handle, PlaybackOutcome.Started);

            AudioTrace.Stop(handle);

            // The event runs for four seconds and was cut after a fraction of one, so
            // this is unambiguously early rather than a natural end.
            yield return AssertBecomes(handle, PlaybackOutcome.StoppedEarly);
        }

        [UnityTest]
        public IEnumerator ASecondInstanceOfAnEventThatRefusesThem_IsRejected()
        {
            // max instances 1, stealing None: the second post is turned away outright.
            // It is created, never granted a voice, and destroyed.
            var first = AudioTrace.Post(MaxOneReject);
            yield return AssertBecomes(first, PlaybackOutcome.Started);

            var second = AudioTrace.Post(MaxOneReject);

            yield return AssertBecomes(second, PlaybackOutcome.Rejected);
            Assert.That(
                AudioTraceRuntime.GetOutcome(first),
                Is.EqualTo(PlaybackOutcome.Started),
                "the sound already playing should have been left alone");

            AudioTrace.Stop(first);
        }

        [UnityTest]
        public IEnumerator AnEventStolenToMakeRoom_IsStolen()
        {
            // max instances 1, stealing Oldest: posting again stops the first, and
            // nobody asked it to. That is the distinction the whole StopRequested
            // mechanism exists to draw.
            var first = AudioTrace.Post(MaxOneSteal);
            yield return AssertBecomes(first, PlaybackOutcome.Started);

            var second = AudioTrace.Post(MaxOneSteal);

            yield return AssertBecomes(first, PlaybackOutcome.Stolen);
            Assert.That(AudioTraceRuntime.GetOutcome(second), Is.EqualTo(PlaybackOutcome.Started));

            AudioTrace.Stop(second);
        }

        [UnityTest]
        public IEnumerator AnEventOverItsLimitWithVirtualizeStealing_IsVirtualized()
        {
            // max instances 1, stealing Virtualize. FMOD virtualises the *quietest*
            // instance rather than refusing the newest, and with two identical sounds
            // that is the one already playing - so it is the first post that goes
            // inaudible while the second takes the voice. Both keep playing; neither is
            // stopped. Worth stating, because the intuitive expectation is the opposite.
            var first = AudioTrace.Post(MaxOneVirtualize);
            yield return AssertBecomes(first, PlaybackOutcome.Started);

            var second = AudioTrace.Post(MaxOneVirtualize);

            yield return AssertBecomes(
                first,
                PlaybackOutcome.Virtualized,
                "the older instance should be playing inaudibly, not stopped");

            Assert.That(AudioTraceRuntime.GetOutcome(second), Is.EqualTo(PlaybackOutcome.Started));

            AudioTrace.Stop(first);
            AudioTrace.Stop(second);
        }

        [UnityTest]
        public IEnumerator A3DEventFarFromTheListener_RecordsTheDistance()
        {
            // The seventh case in the design's table: not a distinct outcome, but the
            // measurement that separates "the sound played and you could not hear it"
            // from "the sound never played".
            const float distance = 40f;

            var handle = AudioTrace.Post(Spatial3D, new Vector3(distance, 0, 0));
            yield return Settle();

            var records = new System.Collections.Generic.List<AudioTraceRecord>();
            AudioTraceRuntime.SnapshotRecords(records);

            var record = records[records.Count - 1];

            Assert.That(record.DistanceToListener, Is.EqualTo(distance).Within(0.5f));
            Assert.That(
                record.DistanceToListener,
                Is.GreaterThan(10f),
                "the fixture event's maximum distance is 10m, so this one is out of range");

            AudioTrace.Stop(handle);
            yield return Settle();
        }

        [UnityTest]
        public IEnumerator AttachingAnInstanceTheGameMade_TracesTheRestOfItsLife()
        {
            // The migration path: existing FMOD code keeps its call site and still shows
            // up in the session.
            RuntimeManager.StudioSystem.getEvent(Basic2D, out var description);
            description.createInstance(out var instance);
            instance.start();

            var handle = FmodAudioTrace.Attach(instance, Basic2D);

            Assert.That(handle.IsValid, Is.True);

            yield return AssertBecomes(handle, PlaybackOutcome.Started);

            AudioTrace.Stop(handle);
            yield return AssertBecomes(handle, PlaybackOutcome.StoppedEarly);

            instance.release();
        }
    }
}
